/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardAgentsRouteImport } from './routes/_dashboard/agents'
import { Route as DashboardStatsRouteImport } from './routes/_dashboard/stats'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardSessionsIndexRouteImport } from './routes/_dashboard/sessions/index'
import { Route as DashboardSessionsSessionIdRouteImport } from './routes/_dashboard/sessions/$sessionId'

const DashboardRoute = DashboardRouteImport.update({ id: '/_dashboard', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({ id: '/agents', path: '/agents', getParentRoute: () => DashboardRoute } as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({ id: '/stats', path: '/stats', getParentRoute: () => DashboardRoute } as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => DashboardRoute } as any)
const DashboardSessionsIndexRoute = DashboardSessionsIndexRouteImport.update({ id: '/sessions/', path: '/sessions/', getParentRoute: () => DashboardRoute } as any)
const DashboardSessionsSessionIdRoute = DashboardSessionsSessionIdRouteImport.update({ id: '/sessions/$sessionId', path: '/sessions/$sessionId', getParentRoute: () => DashboardRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof DashboardAgentsRoute
  '/settings': typeof DashboardSettingsRoute
  '/stats': typeof DashboardStatsRoute
  '/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/sessions/': typeof DashboardSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof DashboardAgentsRoute
  '/settings': typeof DashboardSettingsRoute
  '/stats': typeof DashboardStatsRoute
  '/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/sessions': typeof DashboardSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/agents': typeof DashboardAgentsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/stats': typeof DashboardStatsRoute
  '/_dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/_dashboard/sessions/': typeof DashboardSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents' | '/settings' | '/stats' | '/sessions/$sessionId' | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents' | '/settings' | '/stats' | '/sessions/$sessionId' | '/sessions'
  id: '__root__' | '/' | '/_dashboard' | '/_dashboard/agents' | '/_dashboard/settings' | '/_dashboard/stats' | '/_dashboard/sessions/$sessionId' | '/_dashboard/sessions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': { id: '/_dashboard'; path: ''; fullPath: '/'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_dashboard/agents': { id: '/_dashboard/agents'; path: '/agents'; fullPath: '/agents'; preLoaderRoute: typeof DashboardAgentsRouteImport; parentRoute: typeof DashboardRoute }
    '/_dashboard/stats': { id: '/_dashboard/stats'; path: '/stats'; fullPath: '/stats'; preLoaderRoute: typeof DashboardStatsRouteImport; parentRoute: typeof DashboardRoute }
    '/_dashboard/settings': { id: '/_dashboard/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof DashboardSettingsRouteImport; parentRoute: typeof DashboardRoute }
    '/_dashboard/sessions/': { id: '/_dashboard/sessions/'; path: '/sessions'; fullPath: '/sessions/'; preLoaderRoute: typeof DashboardSessionsIndexRouteImport; parentRoute: typeof DashboardRoute }
    '/_dashboard/sessions/$sessionId': { id: '/_dashboard/sessions/$sessionId'; path: '/sessions/$sessionId'; fullPath: '/sessions/$sessionId'; preLoaderRoute: typeof DashboardSessionsSessionIdRouteImport; parentRoute: typeof DashboardRoute }
  }
}

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardSessionsSessionIdRoute: typeof DashboardSessionsSessionIdRoute
  DashboardSessionsIndexRoute: typeof DashboardSessionsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute,
  DashboardSettingsRoute,
  DashboardStatsRoute,
  DashboardSessionsSessionIdRoute,
  DashboardSessionsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(DashboardRouteChildren)
const rootRouteChildren: RootRouteChildren = { IndexRoute, DashboardRoute: DashboardRouteWithChildren }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>> }
}
